name: 'App: Deploy to WebApp'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.get-version.outputs.image_tag }}
    environment:
      name: 'development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - uses: actions/checkout@v2
    - name: Extract latest version from JSON
      id: get-version
      run: |
        VERSION=$(jq -r '.latest.version' ./app/image_version.json)
        echo "Latest version is: $VERSION"
        echo "image_tag=$VERSION" >> $GITHUB_OUTPUT

    # - name: Deploy to Azure Web App
    #   id: deploy-to-webapp
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: 'app-docker-health-demo-uks'
    #     slot-name: 'production'
    #     publish-profile: ${{ secrets.WebApp_PublishProfile }}
    #     images: 'acrdockerhealthdemouks.azurecr.io/flask-health-app:${{ steps.get-version.outputs.image_tag }}'
    
        # Log in to Azure (required to restart Web App)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Restart the Web App to pull the new image
    - name: Restart Azure Web App
      run: |
        az webapp restart \
          --name 'app-docker-health-demo-uks' \
          --resource-group 'rg-docker-health-demo-uks'