name: 'Terraform Apply'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'

permissions:
  contents: read
  id-token: write
  issues:  write
  pull-requests: write
  checks: write
  actions: write

jobs:
  terraform:
    name: 'Terraform Setup'
    runs-on: ubuntu-latest
    environment: development


    defaults:
      run:
        shell: bash

    steps:
    # Repository Checkout for GitHub Actions
    - name: Checkout
      uses: actions/checkout@v4

    # Install Terraform CLI and configure Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    #Initialise Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: infra/

    # Terraform Formatting 
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: infra/

    #Terraform Plan
    - name: Terraform Plan
      run: terraform plan -input=false -var-file='demo.tfvars'
      working-directory: infra/

    #Terraform Apply to deploy the resources
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false -var-file="demo.tfvars"
      working-directory: infra/
